name: Bug report
description: Report a reproducible problem in the visualization
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Include screenshots and steps to reproduce.
      placeholder: "When I click on ... the ..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser / OS
      placeholder: "e.g., Chrome on macOS"
